slam_toolbox:
  ros__parameters:
    # Robot parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    transform_publish_period: 0.02
    transform_tolerance: 0.1

    # SLAM parameters
    mode: mapping # or localization
    slam_mode: async
    map_update_interval: 5.0
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    scan_topic: /scan
    max_laser_range: 10.0
    resolution: 0.05
    correlation_search_space_scale: 0.1
